name: Build iOS Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          # Install dependencies if any
          echo "Add dependency installs here"

      - name: Build mod
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          # Assuming output is in Keyboard on mobile/build/ios
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: iOS-Mod-Build
          path: "Keyboard on mobile/build/ios"
