name: Build iOS Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build mod
        working-directory: "Keyboard on mobile"
        run: |
          # Run your build command here, example:
          geode build -p ios

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: iOS-Mod-Build
          path: "Keyboard on mobile/build/ios"
